### ISSUE TITLE
Function that reads battery current draw

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#11]
Write a function that reads the current drawn from the specified battery. Battery current can be read from the ADC (Need #4 to be done). More details can be specified once issue is assigned.

**Comment by poornack** [comment]
The function to read battery current has been implemented. Hardware validation is pending. This has to be tested with the Power Board under a load. This measurement is affected by Bug #24.

**Comment by poornack** [comment]
The INA168 current sensor can't detect the low voltage across the shunt resistor. This sensor isn't essential. Current going to the motors and system can still be read from the INA226 sensor. I'm marking this as WONTFIX.
