### ISSUE TITLE
Create a FSM for incoming commands

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#16]
This should be a task that processes incoming commands, and calls the appropriate functions. One of the primary processes of the microcontroller, how it talks with the outside world. Relies on #8 and #9. Expectations are to have simple commands complete (e.g., the "who are you?" command). More complex commands will be added later. This task requires a good design/fleshing out how these commands will be processed.

**Comment by bates-andy123** [comment]
I just imported the motor controller code, issue done
