### ISSUE TITLE
Get I2C Code Working

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#2]
Write some I2C code to work with the STM32F0. Make to use the correct GPIO pins. See the below diagram for the pins we're using. Try and validate changes with an I2C device.
![image](https://user-images.githubusercontent.com/11139202/31302315-ad185320-aab5-11e7-9272-ccc13ce8792b.png)

**Comment by lymacasm** [comment]
Current progress is on lyndon branch

**Comment by poornack** [comment]
Pull Request #27 created and code merged to master.
