### ISSUE TITLE
I2C Humidity And Temperature Sensor

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#5]
**Goal**
The goal of this issue is to create a file with functions that will implement functions to read the temperature and humidity from the humidity/temperature sensor. The sensor uses I2C, and uses the code from #2 to talk to the sensor. 

**Tasks**
The file should expose two functions to the outside world (maybe three if you need an init):

1. get_temperature()
2. get_humidity()

Note that you can use extern to make a function visible to the outside world, and static to hide it. Any helper functions you may need in your file should be static functions.

**Sensor**
The sensor has digikey part number 336-3140-5-ND. Look [here](https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf) for the datasheet. The I2C address is 10000000 for reading and 10000001 for writing (kinda weird, but that's what we've got!)

**Comment by poornack** [comment]
Code merged to master.
