### ISSUE TITLE
I2C Current Sensors

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#6]
**Goal**
Create a file to interface with the current sensors. We currently have 2 sensors, one with address 0b1001111 (motor current), and the other with address 0b1001010 (computer systems current). Depends on #2.

**Tasks**
Create the following functions that are exposed to the outside world (and maybe an init function if needed):

- get_motor_current()
- get_system_current()

**Sensor**
The sensor used has digikey number 296-29034-1-ND. The datasheet can be found [here](http://www.ti.com/lit/ds/symlink/ina226.pdf).

**Comment by poornack** [comment]
Code merged to master.
