### ISSUE TITLE
I2C Pressure Sensor

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#7]
**Goal**
Create a file to interface with the pressure sensor (measures the pressure of the main housing). The I2C address is 0b11101110. Depends on #2.

**Tasks**
Write these function(s) and make them external (this is excluding any init function that may need to be external):

- get_housing_pressure()

**Sensor**
The digikey part number for the sensor is 223-1198-6-ND. The datasheet can be found [here](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=MS5607-02BA03&DocType=Data+Sheet&DocLang=English).

**Comment by poornack** [comment]
Code merged to master.
