### ISSUE TITLE
Get USART working on the Power Board

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Power_Board_1.0#8]
**Task**
Get USART working on the power board. The Power Board uses USART1 for communications. It uses an STM32F0 microcontroller. Commands that come in are terminated with a newline character. The UART should buffer characters coming in, and if it sees a newline character, it should add the preceeding characters to the command buffer. Talk with assignee for #9 to know how to add a command to a buffer.  Might need to do an early merge for these branches, we can talk about this. We'll talk about command structure, it will probably be the same as before, the command structure can be found on the wiki, under the soft start.

**Comment by lymacasm** [comment]
As per previous question, the UART pins are PA9 and PA10 (RX and TX, respectively). You can see the schematic below:

![image](https://user-images.githubusercontent.com/11139202/36957269-18cb582c-1fe8-11e8-84fa-77f10d98901b.png)

**Comment by bates-andy123** [comment]
Who ever does this should look at the code in Motor_Controller_1.0 . It already does most of what you need. You can just improve on it from there

**Comment by anijjar** [comment]
sounds good.

**Comment by bates-andy123** [comment]
I just imported the motor controller code, issue done
